### ISSUE TITLE
Bug: When running a program with Fiddler open, a requests.exceptions.ProxyError is raised

### ISSUE THREAD

**Issue by mossan0101** [xFGhoul/PythonProtector#2]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/xFGhoul/Mai/tree/dev/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/xFGhoul/Mai/blob/dev/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/xFGhoul/Mai/issues) that already report this problem, without success.
- [X] I have checked if the issue is not labeled as 'to do' or 'done' in the [Mai Project](https://github.com/xFGhoul/Mai/projects/1).

### Current Behavior

Your program detects and terminates Fiddler when it is running. However, after that, the following error occurs:

requests.exceptions.ProxyError: HTTPSConnectionPool(host='[www.google.com](http://www.google.com/)', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028868B6D210>: Failed to establish a new connection: [WinError 10061] The target computer actively refused it')))

This error occurred and the main thread did not exit.

### Expected Behavior

I expected the program to send a report after detecting Fiddler and then terminate all threads.

### Steps to Reproduce

Here are the settings for PythonProtector.
# -- Define Constants
LOGGING_PATH = (
    Path.home() / "AppData/Roaming/PythonProtector/logs/[Security].log"
)  # -- This can be any path

# -- Construct Class
security = PythonProtector(
    debug=True,
    modules=[
        "AntiProcess",
        "AntiVM",
        "Miscellaneous",
        "AntiDLL",
        "AntiAnalysis",
        "AntiDump"],
    logs_path=LOGGING_PATH,
    webhook_url=myurl,
    on_detect=[
        "Report",
        "Exit",
        "Screenshot"],
)

# -- Main Code
if __name__ == "__main__":
    SecurityThread = Thread(
        name="Python Protector", target=security.start , daemon=True
    )  # -- Start Before Any Other Code Is Run
    SecurityThread.start()
    # Other Code

1. Launch Fiddler.
2. Execute the program with the above settings

### Additional Information

The operating environment is python3.11 on Windows11. 

When Fiddler is terminated by pythonprotector, my PC loses the ability to communicate despite being connected to the internet. 
Upon checking the proxy settings in Windows, it appears that Fiddler's proxy settings remain even after termination. 
When I manually terminate Fiddler, the proxy settings return to their default state.

As a beginner in Python, I may make mistakes, so please bear with me. Thank you.

**Comment by xFGhoul** [comment]
hey, sorry for the late response, this seems very werid, may i see the full traceback please?

**Comment by xFGhoul** [comment]
and what is dispatched or is any webhook sent?

**Comment by mossan0101** [comment]
I apologize for the delay. Here is the full text. There may be some Japanese mixed in as I am Japanese, so please bear with me


Exception in thread Miscellaneous:
ConnectionRefusedError: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。

During handling of the above exception, another exception occurred:

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001C3947D4D90>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否された ため、接続できませんでした。

During handling of the above exception, another exception occurred:

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C3947D4D90>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。')))

During handling of the above exception, another exception occurred:

requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C3947D4D90>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。')))

**Comment by mossan0101** [comment]
I apologize for the delay. Here is the full text. There may be some Japanese mixed in as I am Japanese, so please bear with me


Exception in thread Miscellaneous:
ConnectionRefusedError: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。

During handling of the above exception, another exception occurred:

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001C3947D4D90>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否された ため、接続できませんでした。

During handling of the above exception, another exception occurred:

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C3947D4D90>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。')))

During handling of the above exception, another exception occurred:

requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C3947D4D90>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。')))

**Comment by xFGhoul** [comment]
> I apologize for the delay. Here is the full text. There may be some Japanese mixed in as I am Japanese, so please bear with me
> 
> Exception in thread Miscellaneous: ConnectionRefusedError: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。
> 
> During handling of the above exception, another exception occurred:
> 
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001C3947D4D90>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否された ため、接続できませんでした。
> 
> During handling of the above exception, another exception occurred:
> 
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C3947D4D90>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。')))
> 
> During handling of the above exception, another exception occurred:
> 
> requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C3947D4D90>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。')))

your internet is the issue here

**Comment by xFGhoul** [comment]
closed due to inactivity.
