### ISSUE TITLE
Feature: Change the content of the webhook

### ISSUE THREAD

**Issue by SORROWMX** [xFGhoul/PythonProtector#9]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/xFGhoul/PythonProtector/tree/dev/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/xFGhoul/Mai/blob/dev/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/xFGhoul/Mai/issues) that already include this feature request, without success.

### Describe the Feature Request

For example, in the code you can add additional information to the webhook

### Describe the Use Case

For example, the login of the user (not the computer) with which the user logged in

**Comment by xFGhoul** [comment]
the `Webhook.send()` method is exposed, so you can theoretically use `your_pyprotector_class.webhook.send(...)`
